#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Auto-generated by parse_logs.py on 2026-05-27 19:06:15
# Source: python/log/*.txt
#
# Sorted by t_ms (unified ms counter, 0 = first event across all devices).
# Fields:
#   t_ms         – unified tick: ms since first event (same style as device ticks)
#   source_file  – which log file this came from
#   device_slot  – slot number of the device that produced this log
#   type         – 'TX' (sent by device) or 'RX' (received by device)
#   tick         – original device tick counter
#   af_slot      – AppliFrame slot field
#   pl_slot      – Payload slot field
#   hubCnt       – hub counter
#   state        – dict hex-label -> 'OFF'/'BLI'/'ON' for all 16 keys
#   dirty        – True if the Dirty flag was set

frames = [
    {
        't_ms': 0000000000,
        'source_file': 'slot_1.txt',
        'device_slot': 1,
        'type': 'TX',
        'tick': 22519,
        'af_slot': 1,
        'pl_slot': 1,
        'hubCnt': 0,
        'state': {'0': 'OFF', '1': 'BLI', '2': 'OFF', '3': 'OFF', '4': 'OFF', '5': 'OFF', '6': 'OFF', '7': 'OFF', '8': 'OFF', '9': 'OFF', 'a': 'OFF', 'b': 'OFF', 'c': 'OFF', 'd': 'OFF', 'e': 'OFF', 'f': 'OFF'},
        'dirty': True,
    },
    {
        't_ms': 0000000091,
        'source_file': 'slot_3.txt',
        'device_slot': 3,
        'type': 'RX',
        'tick': 7811,
        'af_slot': 1,
        'pl_slot': 1,
        'hubCnt': 0,
        'state': {'0': 'OFF', '1': 'BLI', '2': 'OFF', '3': 'OFF', '4': 'OFF', '5': 'OFF', '6': 'OFF', '7': 'OFF', '8': 'OFF', '9': 'OFF', 'a': 'OFF', 'b': 'OFF', 'c': 'OFF', 'd': 'OFF', 'e': 'OFF', 'f': 'OFF'},
        'dirty': True,
    },
    {
        't_ms': 0000000092,
        'source_file': 'slot_9.txt',
        'device_slot': 9,
        'type': 'RX',
        'tick': 11560,
        'af_slot': 1,
        'pl_slot': 1,
        'hubCnt': 0,
        'state': {'0': 'OFF', '1': 'BLI', '2': 'OFF', '3': 'OFF', '4': 'OFF', '5': 'OFF', '6': 'OFF', '7': 'OFF', '8': 'OFF', '9': 'OFF', 'a': 'OFF', 'b': 'OFF', 'c': 'OFF', 'd': 'OFF', 'e': 'OFF', 'f': 'OFF'},
        'dirty': True,
    },
    {
        't_ms': 0000000175,
        'source_file': 'slot_1.txt',
        'device_slot': 1,
        'type': 'RX',
        'tick': 22694,
        'af_slot': 7,
        'pl_slot': 1,
        'hubCnt': 1,
        'state': {'0': 'OFF', '1': 'BLI', '2': 'OFF', '3': 'OFF', '4': 'OFF', '5': 'OFF', '6': 'OFF', '7': 'OFF', '8': 'OFF', '9': 'OFF', 'a': 'OFF', 'b': 'OFF', 'c': 'OFF', 'd': 'OFF', 'e': 'OFF', 'f': 'OFF'},
        'dirty': True,
    },
    {
        't_ms': 0000000248,
        'source_file': 'slot_9.txt',
        'device_slot': 9,
        'type': 'RX',
        'tick': 11716,
        'af_slot': 7,
        'pl_slot': 1,
        'hubCnt': 1,
        'state': {'0': 'OFF', '1': 'BLI', '2': 'OFF', '3': 'OFF', '4': 'OFF', '5': 'OFF', '6': 'OFF', '7': 'OFF', '8': 'OFF', '9': 'OFF', 'a': 'OFF', 'b': 'OFF', 'c': 'OFF', 'd': 'OFF', 'e': 'OFF', 'f': 'OFF'},
        'dirty': True,
    },
    {
        't_ms': 0000000249,
        'source_file': 'slot_3.txt',
        'device_slot': 3,
        'type': 'RX',
        'tick': 7969,
        'af_slot': 7,
        'pl_slot': 1,
        'hubCnt': 1,
        'state': {'0': 'OFF', '1': 'BLI', '2': 'OFF', '3': 'OFF', '4': 'OFF', '5': 'OFF', '6': 'OFF', '7': 'OFF', '8': 'OFF', '9': 'OFF', 'a': 'OFF', 'b': 'OFF', 'c': 'OFF', 'd': 'OFF', 'e': 'OFF', 'f': 'OFF'},
        'dirty': True,
    },
    {
        't_ms': 0000000443,
        'source_file': 'slot_1.txt',
        'device_slot': 1,
        'type': 'RX',
        'tick': 22962,
        'af_slot': 3,
        'pl_slot': 1,
        'hubCnt': 1,
        'state': {'0': 'OFF', '1': 'BLI', '2': 'OFF', '3': 'OFF', '4': 'OFF', '5': 'OFF', '6': 'OFF', '7': 'OFF', '8': 'OFF', '9': 'OFF', 'a': 'OFF', 'b': 'OFF', 'c': 'OFF', 'd': 'OFF', 'e': 'OFF', 'f': 'OFF'},
        'dirty': True,
    },
    {
        't_ms': 0000000498,
        'source_file': 'slot_3.txt',
        'device_slot': 3,
        'type': 'TX',
        'tick': 8218,
        'af_slot': 3,
        'pl_slot': 1,
        'hubCnt': 1,
        'state': {'0': 'OFF', '1': 'BLI', '2': 'OFF', '3': 'OFF', '4': 'OFF', '5': 'OFF', '6': 'OFF', '7': 'OFF', '8': 'OFF', '9': 'OFF', 'a': 'OFF', 'b': 'OFF', 'c': 'OFF', 'd': 'OFF', 'e': 'OFF', 'f': 'OFF'},
        'dirty': True,
    },
    {
        't_ms': 0000000516,
        'source_file': 'slot_9.txt',
        'device_slot': 9,
        'type': 'RX',
        'tick': 11984,
        'af_slot': 3,
        'pl_slot': 1,
        'hubCnt': 1,
        'state': {'0': 'OFF', '1': 'BLI', '2': 'OFF', '3': 'OFF', '4': 'OFF', '5': 'OFF', '6': 'OFF', '7': 'OFF', '8': 'OFF', '9': 'OFF', 'a': 'OFF', 'b': 'OFF', 'c': 'OFF', 'd': 'OFF', 'e': 'OFF', 'f': 'OFF'},
        'dirty': True,
    },
    {
        't_ms': 0000000579,
        'source_file': 'slot_1.txt',
        'device_slot': 1,
        'type': 'RX',
        'tick': 23098,
        'af_slot': 9,
        'pl_slot': 1,
        'hubCnt': 1,
        'state': {'0': 'OFF', '1': 'BLI', '2': 'OFF', '3': 'OFF', '4': 'OFF', '5': 'OFF', '6': 'OFF', '7': 'OFF', '8': 'OFF', '9': 'OFF', 'a': 'OFF', 'b': 'OFF', 'c': 'OFF', 'd': 'OFF', 'e': 'OFF', 'f': 'OFF'},
        'dirty': True,
    },
    {
        't_ms': 0000000635,
        'source_file': 'slot_9.txt',
        'device_slot': 9,
        'type': 'TX',
        'tick': 12103,
        'af_slot': 9,
        'pl_slot': 1,
        'hubCnt': 1,
        'state': {'0': 'OFF', '1': 'BLI', '2': 'OFF', '3': 'OFF', '4': 'OFF', '5': 'OFF', '6': 'OFF', '7': 'OFF', '8': 'OFF', '9': 'OFF', 'a': 'OFF', 'b': 'OFF', 'c': 'OFF', 'd': 'OFF', 'e': 'OFF', 'f': 'OFF'},
        'dirty': True,
    },
    {
        't_ms': 0000000653,
        'source_file': 'slot_3.txt',
        'device_slot': 3,
        'type': 'RX',
        'tick': 8373,
        'af_slot': 9,
        'pl_slot': 1,
        'hubCnt': 1,
        'state': {'0': 'OFF', '1': 'BLI', '2': 'OFF', '3': 'OFF', '4': 'OFF', '5': 'OFF', '6': 'OFF', '7': 'OFF', '8': 'OFF', '9': 'OFF', 'a': 'OFF', 'b': 'OFF', 'c': 'OFF', 'd': 'OFF', 'e': 'OFF', 'f': 'OFF'},
        'dirty': True,
    },
]
