#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Parse device log files from python/log/*.txt and generate
python/simulation/simulation_data.py containing all TXFRAME/RXFRAME events
as a list of dicts with AppliFrame/Payload/State fields.
"""
import re
from datetime import datetime
from pathlib import Path

LOG_DIR = Path(__file__).parent / "log"
OUTPUT_FILE = Path(__file__).parent / "simulation" / "simulation_data.py"


def extract_tick_msg(line):
    """Return (tick:int, msg:str) from a log line, handling PC-timestamp prefix."""
    m = re.search(r'(\d{10}):\s*(.*)', line)
    if m:
        return int(m.group(1)), m.group(2).strip()
    return None, None


def parse_device_slot(lines):
    """Extract the device's own slot number from the EEPROM header section."""
    for line in lines:
        _, msg = extract_tick_msg(line)
        if msg and re.match(r'my_slot\s*=\s*(\d+)', msg):
            return int(re.match(r'my_slot\s*=\s*(\d+)', msg).group(1))
    return None


def parse_frames(source_file, lines):
    """
    Walk through log lines and extract every TXFRAME/RXFRAME block.

    Each block looks like:
        NNNNNNNNNN: TXFRAME (c: XX, YY, ZZ)
        NNNNNNNNNN: AF slot    = X
        NNNNNNNNNN: PL slot    = X
        NNNNNNNNNN: hubCnt     = X
        NNNNNNNNNN: state
        NNNNNNNNNN: label      =  0   1  ... F
        NNNNNNNNNN: State      = OFF BLI ... OFF
        NNNNNNNNNN: Dirty          <- optional; absent means dirty=False
    """
    device_slot = parse_device_slot(lines)
    frames = []
    i = 0

    while i < len(lines):
        tick, msg = extract_tick_msg(lines[i])
        if msg is None:
            i += 1
            continue

        m = re.match(r'(TXFRAME|RXFRAME)\s*\(c:\s*(\d+),\s*(\d+),\s*(\d+)\)', msg)
        if not m:
            i += 1
            continue

        frame = {
            'source_file': source_file,
            'device_slot': device_slot,
            'type': 'TX' if m.group(1) == 'TXFRAME' else 'RX',
            'tick': tick,
            'af_slot': None,
            'pl_slot': None,
            'hubCnt': None,
            'state': {},
            'dirty': False,
        }

        labels = None
        j = i + 1
        max_j = min(i + 15, len(lines))

        while j < max_j:
            _, msg2 = extract_tick_msg(lines[j])
            if msg2 is None:
                j += 1
                continue

            m_af = re.match(r'AF\s+slot\s*=\s*(\d+)', msg2)
            if m_af:
                frame['af_slot'] = int(m_af.group(1))
                j += 1
                continue

            m_pl = re.match(r'PL\s+slot\s*=\s*(\d+)', msg2)
            if m_pl:
                frame['pl_slot'] = int(m_pl.group(1))
                j += 1
                continue

            m_hub = re.match(r'hubCnt\s*=\s*(\d+)', msg2)
            if m_hub:
                frame['hubCnt'] = int(m_hub.group(1))
                j += 1
                continue

            if msg2 == 'state':
                j += 1
                continue

            m_label = re.match(r'label\s*=\s*(.*)', msg2)
            if m_label:
                labels = m_label.group(1).split()
                j += 1
                continue

            m_state = re.match(r'State\s*=\s*(.*)', msg2)
            if m_state and labels is not None:
                values = m_state.group(1).split()
                frame['state'] = {
                    labels[k].lower(): values[k]
                    for k in range(min(len(labels), len(values)))
                }
                j += 1
                continue

            if msg2 == 'Dirty':
                frame['dirty'] = True
                j += 1
                break

            # Any other line ends the frame block
            break

        frames.append(frame)
        i = j

    return frames


def generate_output(all_frames):
    """Render simulation_data.py content from parsed frames."""
    now = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    lines = [
        '#!/usr/bin/env python3',
        '# -*- coding: utf-8 -*-',
        f'# Auto-generated by parse_logs.py on {now}',
        '# Source: python/log/*.txt',
        '#',
        "# Each entry corresponds to one TXFRAME or RXFRAME captured in the device logs.",
        "# Fields:",
        "#   source_file  – which log file this came from",
        "#   device_slot  – slot number of the device that produced this log",
        "#   type         – 'TX' (sent by device) or 'RX' (received by device)",
        "#   tick         – firmware tick counter at the time of the frame",
        "#   af_slot      – AppliFrame slot field",
        "#   pl_slot      – Payload slot field",
        "#   hubCnt       – hub counter",
        "#   state        – dict of hex-label -> 'OFF'/'BLI'/'ON' for all 16 keys",
        "#   dirty        – True if the Dirty flag was set",
        '',
        'frames = [',
    ]

    for f in all_frames:
        state_items = ', '.join(f"'{k}': '{v}'" for k, v in f['state'].items())
        lines += [
            '    {',
            f"        'source_file': '{f['source_file']}',",
            f"        'device_slot': {f['device_slot']},",
            f"        'type': '{f['type']}',",
            f"        'tick': {f['tick']},",
            f"        'af_slot': {f['af_slot']},",
            f"        'pl_slot': {f['pl_slot']},",
            f"        'hubCnt': {f['hubCnt']},",
            f"        'state': {{{state_items}}},",
            f"        'dirty': {f['dirty']},",
            '    },',
        ]

    lines += [']', '']
    return '\n'.join(lines)


def main():
    log_files = sorted(LOG_DIR.glob('*.txt'))
    if not log_files:
        print(f"No .txt files found in {LOG_DIR}")
        return

    all_frames = []
    for log_file in log_files:
        with open(log_file, encoding='utf-8', errors='replace') as fh:
            raw = fh.readlines()
        frames = parse_frames(log_file.name, raw)
        print(f"{log_file.name}: {len(frames)} frames  (device slot {frames[0]['device_slot'] if frames else '?'})")
        all_frames.extend(frames)

    content = generate_output(all_frames)
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(content, encoding='utf-8')

    print(f"\nWrote {len(all_frames)} frames to {OUTPUT_FILE}")

    # Summary per device
    slots = {}
    for f in all_frames:
        key = f['device_slot']
        slots.setdefault(key, {'TX': 0, 'RX': 0})
        slots[key][f['type']] += 1
    print("\nPer device:")
    for slot in sorted(slots):
        print(f"  slot {slot}: {slots[slot]['TX']} TX, {slots[slot]['RX']} RX")

    print(frames)
if __name__ == '__main__':
    main()
